### ISSUE TITLE
Proposed edit on the fight club license

### ISSUE THREAD

**Issue by DonaldTsang** [benlk/misc-licenses#4]
# The Fight Club License
Copyright 2013 Benjamin Lancaster Keith
Copyright 2019 Don. T
1. You do not talk about the FIGHT CLUB LICENSE.
2. You DO NOT talk about the FIGHT CLUB LICENSE.
3. If someone says "stop" or steps down, or gives up, the maintainance is over.
4. Only two maintainers to a project.
5. One project at a time.
6. No CIs (Continuous Integration), no IDEs (Integrated Development Environments).
7. Projects will go on as long as they have to.
8. If this is your first time reading the FIGHT CLUB LICENSE, you HAVE to license your next project under the FIGHT CLUB LICENSE.

**Comment by benlk** [comment]
```diff
--- a/fight-club-license.md
+++ b/fight-club-license.md
@@ -1,19 +1,11 @@
 # The Fight Club License
 Copyright 2013 Benjamin Lancaster Keith
+Copyright 2019 Don. T
 1. You do not talk about the FIGHT CLUB LICENSE.
 2. You DO NOT talk about the FIGHT CLUB LICENSE.
-3. If someone says "stop" or goes limp &mdash;  or taps out &mdash; the project is over.
+3. If someone says "stop" or steps down, or gives up, the maintainance is over.
-4. Only two developers to a project.
+4. Only two maintainers to a project.
 5. One project at a time.
-6. No shirts, no shoes.
+6. No CIs (Continuous Integration), no IDEs (Integrated Development Environments).
 7. Projects will go on as long as they have to.
 8. If this is your first time reading the FIGHT CLUB LICENSE, you HAVE to license your next project under the FIGHT CLUB LICENSE.
```

**Comment by benlk** [comment]
I thank you for the contribution, but are you *sure* you want to be bound by the current version of the FIGHT CLUB LICENSE when you submit these modifications to the FIGHT CLUB LICENSE?

**Comment by DonaldTsang** [comment]
@benlk consider this an enhanced FIGHT CLUB license.
We should also prepare for a PROJECT MAYHEM license as well, now that I though about it.

**Comment by benlk** [comment]
You are free to write a PROJECT MAYHEM license and post it elsewhere, and submit it for inclusion in this repository's list.

I'm not sure that your proposed edits to this license are in keeping with the original spirit of the license, but I'm not going to say you can't fork this license and revise it elsewhere. But I hope to convince you that the proposed edits are not in keeping with the spirit of the license.

As I recall, the original conception of the license treated it as something to be employed in a code jam or hackathon context, where it would make sense for two devs to code until they collapse. I'm not going to dig through or post IRC logs to back that assertion up.

```diff
-3. If someone says "stop" or goes limp &mdash;  or taps out &mdash; the project is over.
+3. If someone says "stop" or steps down, or gives up, the maintainance is over.
```
This change removes the physicality of Fight Club from software development. The Fight Club License isn't about voluntarily maintaining a project; it's a commitment to a project that you may have trouble escaping. Look at the final line of the license; this license isn't meant to be a friendly thing.

```diff
-4. Only two developers to a project.
+4. Only two maintainers to a project.
```

This is a substantial change in meaning. Maintainers may not do any dev work; there may be devs who are not maintainers. The license was meant to limit the scope of a project by limiting the number of devs. When a project has two maintainers and zillions of contributors, it's too big to be interpreted in the context of Fight Club, and thus, is inappropriate for the Fight Club License.

```diff
-6. No shirts, no shoes.
+6. No CIs (Continuous Integration), no IDEs (Integrated Development Environments).
```

Again, this was a joke license for hackathons.

**Comment by DonaldTsang** [comment]
@benlk I would debate that
(3) is basically a duke out between software developers
(4) basically sets that other developers are basically the ring of potential "fighters"
(6) is much more trying to make the license feel more... "on point".
Story adaptation is what I am trying to do.
