### ISSUE TITLE
Add WTFPLv3

### ISSUE THREAD

**Issue by DonaldTsang** [benlk/misc-licenses#5]
- https://github.com/sirkris/System-47-Delay-Loader-for-Multiple-Monitors/blob/master/WTFPLv3.txt
- https://github.com/sirkris/phpMeow/blob/master/WTFPLv3.txt
- https://github.com/sirkris/phpSession/blob/master/WTFPLv3.txt
- https://github.com/sirkris/Agonizing_Death/blob/master/WTFPLv3.txt
```
           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                     Version 3, May 2010

Copyright (C) 2010 by Kris Craig
Olympia, WA USA

Everyone is permitted to copy and distribute verbatim or modified
copies of this license document, and changing it is allowed as long
as the name is changed.

This license applies to any copyrightable work with which it is
packaged and/or distributed, except works that are already covered by
another license. Any other license that applies to the same work
shall take precedence over this one.

To the extent permitted by applicable law, the works covered by this
license are provided "as is" and do not come with any warranty except
where otherwise explicitly stated.


           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION, AND MODIFICATION

 0. You just DO WHAT THE FUCK YOU WANT TO.
```

**Comment by benlk** [comment]
This repo already links to the WTFPL using the link http://www.wtfpl.net/, which contains version 2 of the WTFPL.

Is there a canonical source of the WTFPLv3?

**Comment by DonaldTsang** [comment]
@benlk I would not say it is canonical but I would say this: Someone dared to alter WTFPLv2 to be more "powerful", thus it should been shown that it exists.
